export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';

export const ADMIN_UPDATE_USERS_REQUEST = 'ADMIN_UPDATE_USERS_REQUEST';
export const ADMIN_UPDATE_USERS_SUCCESS = 'ADMIN_UPDATE_USERS_SUCCESS';
export const ADMIN_UPDATE_USERS_FAIL = 'ADMIN_UPDATE_USERS_FAIL';

export const ADMIN_DELETE_USERS_REQUEST = 'ADMIN_DELETE_USERS_REQUEST';
export const ADMIN_DELETE_USERS_SUCCESS = 'ADMIN_DELETE_USERS_SUCCESS';
export const ADMIN_DELETE_USERS_FAIL = 'ADMIN_DELETE_USERS_FAIL';
