export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const ACCOUNT_ACTIVATION_FAIL = 'ACCOUNT_ACTIVATION_FAIL';

export const RESET_MESSAGE = 'RESET_MESSAGE';