export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';

export const SAVE_FEATURED_COURSES_REQUEST = 'SAVE_FEATURED_COURSES_REQUEST';
export const SAVE_FEATURED_COURSES_SUCCESS = 'SAVE_FEATURED_COURSES_SUCCESS';
export const SAVE_FEATURED_COURSES_FAIL = 'SAVE_FEATURED_COURSES_FAIL';

export const DELETE_COURSE_VIDEOCLASS_REQUEST = 'DELETE_COURSE_VIDEOCLASS_REQUEST';
export const DELETE_COURSE_VIDEOCLASS_SUCCESS = 'DELETE_COURSE_VIDEOCLASS_SUCCESS';
export const DELETE_COURSE_VIDEOCLASS_FAIL = 'DELETE_COURSE_VIDEOCLASS_FAIL';

export const CLASS_WATCHED_UPDATED_REQUEST = 'CLASS_WATCHED_UPDATED_REQUEST'
export const CLASS_WATCHED_UPDATED_RESET = 'CLASS_WATCHED_UPDATED_RESET'
