export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';

export const SAVE_FEATURED_COURSES_REQUEST = 'SAVE_FEATURED_COURSES_REQUEST';
export const SAVE_FEATURED_COURSES_SUCCESS = 'SAVE_FEATURED_COURSES_SUCCESS';
export const SAVE_FEATURED_COURSES_FAIL = 'SAVE_FEATURED_COURSES_FAIL';