export const CHECK_MEMBERSHIP = 'CHECK_MEMBERSHIP';
export const CHECK_MEMBERSHIP_REQUEST = 'CHECK_MEMBERSHIP_REQUEST';
export const CANCEL_MEMBERSHIP = 'CANCEL_MEMBERSHIP';
export const RESUBSCRIBE_MEMBERSHIP = 'RESUBSCRIBE_MEMBERSHIP';
export const CANCEL_MEMBERSHIP_REQUEST = 'CANCEL_MEMBERSHIP_REQUEST';