export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';

export const FIND_USER_REQUEST = 'FIND_USER_REQUEST';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const FIND_USER_FAIL = 'FIND_USER_FAIL';
